version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Decode Client Secret
          command: echo "$CLIENT_SECRET" | base64 -i --decode > ./client-secret.json
      - run:
          name: Invoke Cloud Functions
          command: curl $FUNCTION_URL -H "Authorization:Bearer $(GOOGLE_APPLICATION_CREDENTIALS=./client-secret.json gcloud auth application-default print-access-token)"
    branches:
      only:
        - develop