version: 2
jobs:
  build:
    docker:
      - image: byrnedo/alpine-curl:latest
    steps:
      - checkout
      - run:
          name: Invoke Cloud Functions
          command: curl $FUNCTION_URL
    branches:
      only:
        - master